name: Build Pull Request
on: pull_request

jobs:
  build:
    name: Build pull request
    runs-on: macos-13
    env:
        JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '21.0.1'
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build
        id: build
        run: ./gradlew --warning-mode all check build -x test

      - name: Run Unit Tests
        id: unit_test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./gradlew --no-daemon --max-workers=2 --warning-mode=all test --continue --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test-results/test/**/*.xml'

  publish-test-results:
    name: Publish Unit Test Results
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.18
        with:
          check_name: "Unit Test Results"
          files: "**/*.xml"
          fail_on: test failures
          hide_comments: all but latest
          comment_mode: update last
          compare_to_earlier_commit: true
          pull_request_build: merge
          check_run_annotations: all tests, skipped tests